"use client";

import {
    SiReact,
    SiMongodb,
    SiNodedotjs,
    SiTailwindcss,
    SiGreensock,
    SiFramer,
    SiThreedotjs,
    SiJavascript,
    SiTypescript,
    SiOpenai,
    SiNextdotjs,
    SiPostgresql,
    SiCss3,
    SiExpress,
    SiChartdotjs,
    SiJsonwebtokens,
    SiWebgl,
    SiVite,
    SiPrisma,
    SiFlask,
    SiNumpy,
    SiOpencv,
    SiOdoo,
    SiHtml5,
    SiNetlify,
    SiFirebase,
    SiVercel,
    SiSocketdotio,
    SiRedis,
    SiAmazon,
    SiPostman,
    SiBun,
    SiFigma,
    SiPytorch,
    SiTensorflow
} from "react-icons/si";
import {
    Cuboid as Cube,
    Scroll,
    Code2,
    Cpu,
    ScanEye,
    BrainCircuit,
    FileCode,
    Database,
    ShieldCheck,
    Boxes,
    Smartphone,
    LineChart,
    Accessibility,
    Server,
    Layers,
    Palette,
    Zap,
    Cloud,
    Tag,
    Box,
    LayoutDashboard,
    Radio,
    Blocks
} from "lucide-react";
import React from "react";

interface TechIconProps {
    name: string;
}

export default function TechIcon({ name }: TechIconProps) {
    const iconMap: Record<string, React.ElementType> = {
        "React": SiReact,
        "React Native": SiReact,
        "MongoDB": SiMongodb,
        "Node.js": SiNodedotjs,
        "Tailwind CSS": SiTailwindcss,
        "Lenis": Scroll,
        "GSAP": SiGreensock,
        "ScrollTrigger": SiGreensock,
        "Framer Motion": SiFramer,
        "Three.js": SiThreedotjs,
        "JavaScript": SiJavascript,
        "TypeScript": SiTypescript,
        "OpenAI": SiOpenai,
        "OpenAI API": SiOpenai,
        "Next.js": SiNextdotjs,
        "PostgreSQL": SiPostgresql,
        "CSS": SiCss3,
        "CSS3": SiCss3,
        "CSS Animations": SiCss3,
        "HTML": Code2,
        "HTML5": SiHtml5,
        "Python": Code2,
        "AI": Cpu,
        "Express.js": SiExpress,
        "Chart.js": SiChartdotjs,
        "JWT Authentication": SiJsonwebtokens,
        "WebGL": SiWebgl,
        "Vite": SiVite,
        "Prisma ORM": SiPrisma,
        "Computer Vision": ScanEye,
        "CNN Models": BrainCircuit,
        "Flask": SiFlask,
        "NumPy": SiNumpy,
        "OpenCV": SiOpencv,
        "Odoo Framework": SiOdoo,
        "XML Views": FileCode,
        "ORM": Database,
        "RBAC": ShieldCheck,
        "ERP Modules": Boxes,
        "Responsive Design": Smartphone,
        "SEO Optimization": LineChart,
        "Accessibility": Accessibility,
        "Netlify": SiNetlify,
        "REST APIs": Server,
        "Firebase": SiFirebase,
        "Mobile UX": Smartphone,
        "Parallax Effects": Layers,
        "UI/UX Design": Palette,
        "Component Architecture": Blocks,
        "Performance Optimization": Zap,
        "Vercel": SiVercel,
        "Socket.io": SiSocketdotio,
        "WebSockets": Radio,
        "Redis": SiRedis,
        "Dashboard UI": LayoutDashboard,
        "State Management": Database,
        "SaaS Architecture": Cloud,
        "Web Performance": Zap,
        "Branding": Tag,
        "UI Components": Box,
        "Bun": SiBun,
        "AWS": SiAmazon,
        "Postman": SiPostman,
        "Figma": SiFigma,
        "PyTorch": SiPytorch,
        "TensorFlow Lite": SiTensorflow,
    };

    // Color mapping for each technology
    const colorMap: Record<string, string> = {
        "React": "text-[#61DAFB]",
        "React Native": "text-[#61DAFB]",
        "MongoDB": "text-[#47A248]",
        "Node.js": "text-[#339933]",
        "Tailwind CSS": "text-[#06B6D4]",
        "Lenis": "text-zinc-600 dark:text-zinc-400",
        "GSAP": "text-[#88CE02]",
        "ScrollTrigger": "text-[#88CE02]",
        "Framer Motion": "text-[#0055FF]",
        "Three.js": "text-black dark:text-white",
        "JavaScript": "text-[#F7DF1E]",
        "TypeScript": "text-[#3178C6]",
        "OpenAI": "text-[#10A37F]",
        "OpenAI API": "text-[#10A37F]",
        "Next.js": "text-black dark:text-white",
        "PostgreSQL": "text-[#4169E1]",
        "CSS": "text-[#1572B6]",
        "CSS3": "text-[#1572B6]",
        "CSS Animations": "text-[#1572B6]",
        "HTML": "text-[#E34F26]",
        "HTML5": "text-[#E34F26]",
        "Python": "text-[#3776AB]",
        "AI": "text-purple-600 dark:text-purple-400",
        "Express.js": "text-black dark:text-white",
        "Chart.js": "text-[#FF6384]",
        "JWT Authentication": "text-pink-600",
        "WebGL": "text-[#990000]",
        "Vite": "text-[#646CFF]",
        "Prisma ORM": "text-[#2D3748] dark:text-white",
        "Flask": "text-black dark:text-white",
        "NumPy": "text-[#013243] dark:text-[#4d77cf]",
        "OpenCV": "text-[#5C3EE8]",
        "Odoo Framework": "text-[#714B67]",
        "Netlify": "text-[#00C7B7]",
        "Firebase": "text-[#FFCA28]",
        "Vercel": "text-black dark:text-white",
        "Socket.io": "text-black dark:text-white",
        "Redis": "text-[#DC382D]",
        "Bun": "text-black dark:text-white",
        "AWS": "text-[#FF9900]",
        "Postman": "text-[#FF6C37]",
        "Figma": "text-[#F24E1E]",
        "PyTorch": "text-[#EE4C2C]",
        "TensorFlow Lite": "text-[#FF6F00]",
    };

    const Icon = iconMap[name] || Code2;
    const iconColor = colorMap[name] || "text-zinc-600 dark:text-zinc-400";

    return (
        <div className="group/icon relative inline-flex items-center justify-center">
            <div className="p-2 bg-zinc-100 dark:bg-zinc-800 rounded-md border border-zinc-200 dark:border-zinc-700/50 hover:border-zinc-300 dark:hover:border-zinc-600 transition-all hover:shadow-sm">
                <Icon className={`h-5 w-5 ${iconColor} transition-transform group-hover/icon:scale-110`} />
            </div>

            {/* Tooltip */}
            <div className="absolute -top-10 left-1/2 -translate-x-1/2 px-2 py-1 bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900 text-xs font-semibold rounded opacity-0 group-hover/icon:opacity-100 transition-opacity whitespace-nowrap pointer-events-none z-10">
                {name}
                {/* Tiny triangle for tooltip arrow */}
                <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-2 h-2 bg-zinc-900 dark:bg-zinc-100 rotate-45" />
            </div>
        </div>
    );
}
